### ISSUE TITLE
Segmentation fault on Ubuntu 20.04

### ISSUE THREAD

**Issue by gc-robotics** [xdspacelab/openvslam#510]
```
11 0x00007ffff7d5fa71 in openvslam::system::feed\_monocular\_frame(cv::Mat const&, double, cv::Mat const&) () at /home/alpha/Projects/r/install/openvslam/lib/libopenvslam.so
#12 0x000055555556db7d in std::thread::\_State\_impl<std::thread::\_Invoker<std::tuple<mono\_tracking(std::shared\_ptr<openvslam::config> const&, std::**cxx11::basic\_string<char, std::char\_traits<char>, std::allocator<char> > const&, std::**cxx11::basic\_string<char, std::char\_traits<char>, std::allocator<char> > const&, std::**cxx11::basic\_string<char, std::char\_traits<char>, std::allocator<char> > const&, unsigned int, bool, bool, bool, std::**cxx11::basic\_string<char, std::char\_traits<char>, std::allocator<char> > const&)::{lambda()#1}> > >::\_M\_run() ()
#13 0x00007ffff65e9d84 in () at /lib/x86\_64-linux-gnu/libstdc++.so.6
#14 0x00007ffff7c8b609 in start\_thread (arg=<optimised out>) at pthread\_create.c:477
#15 0x00007ffff6428293 in clone () at ../sysdeps/unix/sysv/linux/x86\_64/clone.S:95
(gdb)
```

**Comment by mirellameelo** [comment]
According to the [documentation](https://openvslam.readthedocs.io/en/master/installation.html), Openvslam was not tested for Ubuntu 20.04. Were you able to make it work?
